### ISSUE TITLE
Can't run  flask example application flaskr in windows

### ISSUE THREAD

**Issue by hengaini2055** [inveniosoftware/flask-cli#24]
I use the following modules in windows:
   `pip freeze
click==6.7
Flask==0.12.2
-e git+https://github.com/pallets/flask.git@851eaa4db7cef513dae35286d816867d68a72049#egg=flaskr&subdirectory=examples\flaskr
itsdangerous==0.24
Jinja2==2.9.6
MarkupSafe==1.0
Werkzeug==0.12.2`
   According the document of flaskr, I set FLASK_APP=flaskr.factory:create_app(). When I run command `flask run`, I get the following errors:
   RuntimeError: Failed to find application in module "flaskr.factory"

**Comment by lnielsen** [comment]
Hi,

The error you are getting is unrelated to Flask-CLI because 1) you are installing Flask v0.12.2 and 2) you are not installing Flask-CLI library. Flask-CLI is a back port of the CLI feature from Flask v0.11+ to v0.10.

The error you are getting is most likely because you didn't install flaskr properly or you have to change directory to ``examples/flaskr`` or similar. Essentially from Python you  should be able to import the module:

```python
>>> from flask.factory import create_app
```

If it fails, then ``flask run`` will also fail.
